name: Java CI with Maven
 
env:
  NAME: 'My Action'
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Print name
      run: echo "$NAME"
