name: Workflow Commands
on: [push]

jobs:
  workflow1:
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1 ]"
        run:  |
            echo "VAL=durga" >> $GITHUB_ENV
      - name: "Step 1 ]"
        run:  |
            echo $VAL
      - name: "Debug Messages"
        run: |
            echo "::debug::Set the Octocat variable"
      - name: "Group Message"
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "Another group"
            echo "::endgroup::"
